/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nwillc' at '12/4/15 10:32 PM' with Gradle 2.7
 *
 * @author nwillc, @date 12/4/15 10:32 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
